services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb+srv://root:123Shriramsmd@free-cluster.q9zqz.mongodb.net/mern-bookstore-db?retryWrites=true&w=majority&appName=Free-Cluster
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
